### ISSUE TITLE
interference on 101.8 MHz

### ISSUE THREAD

**Issue by Mike86-CZE** [PE5PVB/TEF6686_ESP32#127]
With version 2.0, I have interference at a frequency of 101.8 MHz when the display is running (and redraws).  If the display turns off, the interference disappears.  I had similar interference to a lesser extent with version 1.18 at the frequency of 90.1 MHz, here it is now fine.

**Comment by PE5PVB** [comment]
The problem is caused by interference from the display. When you alter the clock frequency, the problem will move to another frequency. This has to do with hardware. I'm still playing with the clock-speed and try to get the interference out of the FM band, but since it's 20MHz wide it's almost inpossible.
