### ISSUE TITLE
RT+ first shows mylanguage[0]

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#203]
When a RT+ transmission is received for the first time (after a cold start) RT+ will display mylanguage[0] from the language file until mylanguage[112ff] are shown.

If you set the language to - for example - German, the text is "Deutsch" of course.

I guess you need to wait till RT+ items are received and not just check for 0x4BD7. 

![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/886075c3-d154-4974-94fe-4c1417ea4514)

Remark: I only have this very disturbed radio station using RT+ here.

**Comment by PE5PVB** [comment]
That is strange. Can you check again in a next update?

**Comment by lxsxl** [comment]
It is still the same in yesterdays beta:

![RT+ language](https://github.com/PE5PVB/TEF6686_ESP32/assets/140750201/4252fd54-e866-4cc3-8df8-25a81cc3add9)

For me it seems that it happens when the device is switched on and then quickly switched to advanced RDS-screen. It will take a moment until RT+ is detected and that is the moment where the language can be seen, sometimes only a part of a second, somtimes it seems to get stuck,

**Comment by PE5PVB** [comment]
Ah ok. It seems that you received block 3A with the RT+ application init, but not on of the assigned RT+ blocks. I'll fix the problem.
