### ISSUE TITLE
TA indicator always on for EON stations

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#317]
I know that the standard says, TP = 0 and TA = 1 means EON, but the TA indicator is always on which is misunderstanding. 

My expectation for such cases is, TA is only shown when another station from EON is currently having an active TA ...

**Comment by PE5PVB** [comment]
If you want to have accurate information about the current station it should be like this:

TP - TA
0  0  No traffic service possible at all on or via this service
0  1  Traffic service provided via one or more EON cross-referenced services
1  0  Traffic service provided on this service and also possibly via EON services
1  1  Traffic report in progress on this service

I currently show the status of these flags, so you are correct. Question is, what do you want to show. What I can do is detect in the EON section if any of the stations do have a TA and then set the flag high, or leave it like it is.

**Comment by lxsxl** [comment]
I would say keep  the raw indicators as they are because it is conform with the RDS specification. You could probably add further EON information (i. e. TP / TA / PTY) in the EON/AF view. But there is already no space left. Probably divide this screen into two seperate screens? Don't know if it is possible...

**Comment by PE5PVB** [comment]
Maybe an seperate EON screen. But this is not an answer on the issue. I'll ask the community about this.

**Comment by PE5PVB** [comment]
I'd to ask the community a question regarding the TA symbol.
Currently it shows the TA and TP flag as transmitted by the received radiostation. But when there is EON, the TA flag is always high. I like to know your preference on this.
A. Keep it like it is.
B. Only show TA when a traffic announcement is going on, on the tuned radiostation.
C. Also show TA when a traffic announcement is going on on another radiostation in the EON.

**Comment by lxsxl** [comment]
Yes that's right. But RDS specification says that TP = 0 and TA = 1 does only mean that there is an EON service that provides traffic information and not that it actually transmits those information. If this information is also needed you could probably change the color of the TA-indicator if TP = 0 AND TA = 1 AND EON-TP = 1 AND EON-TA = 1.

**Comment by lxsxl** [comment]
As the majority tends to B., I have two questions:
1. What is the trigger for the EON-indicator, presence of group 14A or TP=0 and TA=1?
2. What is the trigger for the TA-indicator, TA=1 in group 0A or in group 15B or the first received of those?

**Comment by PE5PVB** [comment]
1. When Group 14A is present
2. Bit 4 in block B in group 0A or 0B

**Comment by mtv-alex** [comment]
If we talk about a household receiver (car radio), then the indication of this flag goes as TР (when TР = 0, TA = 1). Since I have two stations transmitting TР=0/TA=1, I didn't see any indication on the receiver display.
That's why I pointed to this point. As for me, the flag indication can be left. If traffic information is transmitted at the station, only TP will be lit. And at the time of traffic information - TР and TA. Stations where only the TA is lit simply informs that there is a switch to another station during traffic information. TР=0/TA=1 does not make any adjustments to the operation of the receiver (for example, increasing the volume) until the command to switch comes.

**Comment by andimik** [comment]
TR?

**Comment by mtv-alex** [comment]
> TR?

Edited.

I will also add that even if EON is not transmitted, it is possible to transmit TP =0/TA =1. The behavior of the receiver will not change either. It just won't meet the standard a bit. Such moments can also take place.

**Comment by PE5PVB** [comment]
Almost every station has TP set true, because otherwise a lot of radio's won't stop on that station during channel seeking.

**Comment by mtv-alex** [comment]
As for me, there should be some kind of identification. Or as in car radios (when TP=0/TA=1, TR is lit on the display. But then somewhere really show to show that it is the expression TP=0/TA=1 that is accepted) or leave it as it is now.
Ignore this point is not worth it. There are many such stations in Europe broadcasting according to this scheme.
It is incorrect to write TA/EON, because it means that the 15B group is being transmitted. And it works at the moment when we want to switch the listener to a station with traffic information.

**Comment by PE5PVB** [comment]
Didn't you mix up TP (Traffic Program) and TA (Traffic announcement)?

Well, in EON information I can get the actual program which is broadcasting the TA.

**Comment by mtv-alex** [comment]
Maybe we're starting to get a little confused. The question is: whether to show the burning TA flag when the TP flag is inactive (expression TP=0/TA=1). Do I understand the problem correctly? If this is the case, then I suggest not to change anything - leave it like this now. This situation should also be displayed. At the moment, the receiver is showing as it should.

**Comment by PE5PVB** [comment]
No, discussion is about show the flags as transmitted, or show the flags as they should be processed.
If TP is 0 and TA is 1, the radio knows that there could be another station in the EON who will transmit traffic announcements.

When displaying the flags as transmitted, in this case the TA is always on, which could suggest that a traffic annoucement is going on.

**Comment by mtv-alex** [comment]
It must be shown as the station transmits. This is the true logic of any RDS decoder (Pira, Deva, WorldCast, etc.). A constantly burning flag does not mean that traffic information is transmitted. The designation of road information is indicated only as TP=1/TA=1. I emphasize - in the current version, the work of this moment is correct and logical.

**Comment by PE5PVB** [comment]
Yes, but the noob user will think that there is a problem because the traffic annoucement flag is still on while music is played.

**Comment by mtv-alex** [comment]
Well, the user may not understand AF method B (where there are a lot of nuances). Even for me, it's confusing. And the situation with TP =0 / TA =1 is ubiquitous: there are in Germany, France, Great Britain and many other places. I have not seen any of the users ask the authors of the decoders to change something at this moment. Allegedly, this is misleading for the user. No, that's just the way the RDS works. If we decode and display most of the functions that the station transmits, then we must display how it is decoded. Without making any changes at the receiver level. This is my strictly personal opinion.

**Comment by PE5PVB** [comment]
For now I will leave it as it is. Just show the raw flags.

**Comment by mtv-alex** [comment]
I also want to add: they wrote that the combination TP = 0 / TA = 1 is only strictly shown when there is a 14 A group (EON). Ideally and according to the standard, yes. I attach two photos that it is possible to transmit the combination TP = 0 / TA = 1 having an EON, or simply not having it. I just turned off group 14A at home to show an example. There may also be such cases - engineers have configured something wrong or something else. There are all sorts of situations.
![EON 1](https://github.com/PE5PVB/TEF6686_ESP32/assets/147340942/7b6e3dfc-2165-4068-b0ae-985ceae5546b)
![EON2](https://github.com/PE5PVB/TEF6686_ESP32/assets/147340942/3127f7a2-8ec8-4965-9c7a-296da849810e)
