### ISSUE TITLE
PI and PS on memories

### ISSUE THREAD

**Issue by lxsxl** [PE5PVB/TEF6686_ESP32#539]
If you recall a memory and there is no RDS signal the saved codes are shown in primary colour. Should be secondary colour until RDS is received again.

**Comment by PE5PVB** [comment]
Should be fixed.

**Comment by PE5PVB** [comment]
Please confirm.

**Comment by lxsxl** [comment]
Yea, it is working fine now. I close this issue.

**Comment by lxsxl** [comment]
.

**Comment by lxsxl** [comment]
.

**Comment by Mike86-CZE** [comment]
https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/d50ea213-8c6b-40e6-8394-9ac5431c543f

The problem is still there.  If the previous memory ch. had RDS reception, saved PS and PI is the primary color.  If the previous memory ch. did not have RDS reception, saved PS and PI is the correct secondary color for the next memory.

**Comment by PE5PVB** [comment]
Fixed.

**Comment by lxsxl** [comment]
My tests with the latest code were fine. Seems that it works correct.
