### ISSUE TITLE
AutoScan plug in cannot restart scanning once a signal if found

### ISSUE THREAD

**Issue by numerci** [PE5PVB/TEF6686_ESP32#591]
Preconditions:
A. DX scan options: Memory channels=Only
B. DX scan options: Auto cancel scan = Signal or Correct PI
Steps to reproduce:
1. Start an AutoScan using the WebServer plug in.
2. Wait till a signal is found (constant signal).
3. Press again the AutoScan button from the WebServer.
Result: The scan doesn't start anymore.
Note: Probably this appeared a few versions back when the fix to start from the last user frequency was added. Actually it should be the next one otherwise we enter a loop.

**Comment by PE5PVB** [comment]
If it works correct on the radio and not with the plugin, then it's not a problem in the ESP32 firmware. Just because of this:  
      case 'J':  
       byte scandxtemp;  
       scandxtemp = atol(buff + 1);  
       if (scandxtemp == 0 && scandxmode) cancelDXScan();  
       if (scandxtemp == 1 && !scandxmode) startFMDXScan();  
       DataPrint("J" + String(scandxtemp) + "\\n");  
       break;

So it's just an action, nothing more.

**Comment by numerci** [comment]
It does the same on TEF after a DX Scan. if it stops and if you press the Band button normally it starts again but in this case is not starting like the AutoScanner does.

**Comment by PE5PVB** [comment]
Fixed.

**Comment by numerci** [comment]
Thank you very much :)

**Comment by numerci** [comment]
Works fine both from the TEF and from the AutoScanner on RC14. Closed
